name: 🚀 Generate Data

on:
    push:
        branches: ["main"] # runs on push to main
    schedule:
        - cron: "0 0 * * *" # runs every day

jobs:
    run:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v6
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
            - run: pip install cwltool

            - run: cwltool --quiet --outdir index workflows/workflow.cwl job.yml
            - uses: stefanzweifel/git-auto-commit-action@v7
              with:
                  commit_message: |
                      Updated Metrics data
                  commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
